FROM bitwalker/alpine-elixir-phoenix:latest
#FROM phoenix/alpine:1.3.0

ENV MIX_ENV=prod

# Cache elixir deps
RUN mkdir config
COPY config/* config/
COPY mix.exs mix.lock ./

RUN mix do deps.get, deps.compile

RUN mkdir assets
COPY assets/* assets/

COPY . .

RUN true \
  && cd assets \
  && npm install \
  && node_modules/brunch/bin/brunch build --production \
  && cd ..

RUN mix do compile, phx.digest, release --env=prod --verbose
