use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# NoaWeb.Endpoint.load_from_system_env/1 dynamically.
# Any dynamic configuration should be moved to such function.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :noa, NoaWeb.Endpoint,
  #on_init: {NoaWeb.Endpoint, :load_from_system_env, []},
  server: true,
  root: ".",
  load_from_system_env: true,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :noa, NoaWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :noa, NoaWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :noa, NoaWeb.Endpoint, server: true
#
config :phoenix, :serve_endpoints, true

# Finally import the config/prod.secret.exs
# which should be versioned separately.
#import_config "prod.secret.exs"

config :noa, Noa.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "${DB_USER}",
  password: "${DB_PASSWORD}",
  database: "${DB_NAME}",
  hostname: "${DB_HOST}",
  pool_size: 10

config :noa, :stubhandler,
  handler: Noa.Tokens.OpaqueStubHandler,
  options: [secret: "juXKNtKy1rmhTnyzlTx3R9QCAJFcJOpNjxOHRpgxbUw"]

config :noa, :ssl_config,
  port:     "${SSL_PORT}",
  keyfile:  "${NOA_SSL_KEY_PATH}",
  certfile: "${NOA_SSL_CERT_PATH}"

config :noa, :resource_owners,
  provider: Noa.ROProviders.QuickstartProvider,
  options: [creds_file: "${NOA_RO_QUICKSTART_CREDS_FILE}"]

config :comeonin,
  bcrypt_log_rounds: 10,
  pbkdf2_rounds: 100_000
